scrape_configs:
  - job_name: "gateway"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["192.168.29.190:8080"]
  - job_name: "productservice"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.29.190:3002"]